#include <pspkernel.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include <psputility.h>
#include <psputility_msgdialog.h>
#include <psputility_netconf.h>
#include <psputility_netparam.h>
#include <psputility_savedata.h>
#include <psputility_gamesharing.h>
#include <psputility_htmlviewer.h>
#include <psputility_sysparam.h>
#include <psputility_osk.h>
#include <psputility_netmodules.h>
#include <psputility_avmodules.h>
#include <psputility_usbmodules.h>
#include <psputility_modules.h>

#include "../../main/shared.h"

PSP_MODULE_INFO("sceUtility",PSP_MODULE_USER,1,1);
PSP_NO_CREATE_MAIN_THREAD();

JS_FUN(LoadModule){
	*rval = I2J(sceUtilityLoadAvModule(J2I(argv[0])));
	return JS_TRUE;
}
JS_FUN(UnloadModule){
	*rval = I2J(sceUtilityUnloadAvModule(J2I(argv[0])));
	return JS_TRUE;
}
JS_FUN(LoadAvModule){
	*rval = I2J(sceUtilityLoadAvModule(J2I(argv[0])));
	return JS_TRUE;
}
JS_FUN(UnloadAvModule){
	*rval = I2J(sceUtilityUnloadAvModule(J2I(argv[0])));
	return JS_TRUE;
}
JS_FUN(LoadUsbModule){
	*rval = I2J(sceUtilityLoadUsbModule(J2I(argv[0])));
	return JS_TRUE;
}
JS_FUN(UnloadUsbModule){
	*rval = I2J(sceUtilityUnloadUsbModule(J2I(argv[0])));
	return JS_TRUE;
}
JS_FUN(LoadNetModule){
	*rval = I2J(sceUtilityLoadNetModule(J2I(argv[0])));
	return JS_TRUE;
}
JS_FUN(UnloadNetModule){
	*rval = I2J(sceUtilityUnloadNetModule(J2I(argv[0])));
	return JS_TRUE;
}
JS_FUN(GameSharingInitStart){
	char *name;
	pspUtilityGameSharingParams params;
	memset(&params, 0, sizeof(params));
	params.base.size = sizeof(params);
	if (!js_convertArguments(argc, argv, "iiiiiiilsii",
			&params.base.language,//ENGLISH:1;FRENCH:2;SPANISH:3;GERMAN:4;ITALIAN:5;DUTCH:6;PORTUGUESE:7;RUSSIAN:8;KOREAN:9;CHINESE_T:10;CHINESE_S:11;
			&params.base.buttonSwap,//CIRCLE:0;CROSS:1;
			&params.base.graphicsThread,//17
			&params.base.accessThread,//19
			&params.base.fontThread,//18
			&params.base.soundThread,//16
			&params.datasize,
			&name,
			&params.mode,//1:FILE;2:MEMORY
			&params.datatype))//1:SINGLE;2:MULTIPLE
		return JS_FALSE;
	memcpy(&params.name, name, 8);
	*rval = I2J(sceUtilityGameSharingInitStart(&params));
	return JS_TRUE;
}
JS_FUN(GameSharingUpdate){
	sceUtilityGameSharingUpdate(1);
	return JS_TRUE;
}
JS_FUN(GameSharingShutdownStart){
	sceUtilityGameSharingShutdownStart();
	return JS_TRUE;	
}
JS_FUN(GameSharingGetStatus){
	*rval = I2J(sceUtilityGameSharingGetStatus());//NONE:0;INIT:1;VISIBLE:2;QUIT:3;FINISHED:4;
	return JS_TRUE;	
}
JS_FUN(MsgDialogUpdate){
	sceUtilityMsgDialogUpdate(1);
	return JS_TRUE;	
}
JS_FUN(MsgDialogGetStatus){
	*rval = I2J(sceUtilityMsgDialogGetStatus());
	return JS_TRUE;	
}
JS_FUN(MsgDialogAbort){
	*rval = I2J(sceUtilityMsgDialogAbort());
	return JS_TRUE;	
}
JS_FUN(MsgDialogShutdownStart){
	sceUtilityMsgDialogShutdownStart();
	return JS_TRUE;	
}
JS_FUN(GetSystemParamInt){
	int value;
	sceUtilityGetSystemParamInt(J2I(argv[0]), &value);
	*rval = I2J(value);
	return JS_TRUE;
}
JS_FUN(SetSystemParamInt){
	*rval = I2J(sceUtilitySetSystemParamInt(J2I(argv[0]),J2I(argv[1])));
	return JS_TRUE;
}
char ParamString[255];
JS_FUN(GetSystemParamString){
	//sceUtilityGetSystemParamString(J2I(argv[0]), ParamString,J2I(argv[1]));
	*rval = STRING_TO_JSVAL(js_newString("saphire"));
	return JS_TRUE;
}
JS_FUN(SetSystemParamString){
	*rval = I2J(sceUtilitySetSystemParamString(J2I(argv[0]),J2S(argv[0])));
	return JS_TRUE;
}
pspUtilityDialogCommon objectToBase(JSObject* bobj,pspUtilityDialogCommon* base,size_t size){
	base->size=size;
	base->language=J2I(js_getProperty(bobj,"language"));
	base->buttonSwap=J2I(js_getProperty(bobj,"buttonSwap"));
	base->graphicsThread=J2I(js_getProperty(bobj,"graphicsThread"));
	base->accessThread=J2I(js_getProperty(bobj,"accessThread"));
	base->fontThread=J2I(js_getProperty(bobj,"fontThread"));
	base->soundThread=J2I(js_getProperty(bobj,"soundThread"));
	base->result=J2I(js_getProperty(bobj,"result"));
	return *base;
}
pspUtilityMsgDialogParams dialog;
JS_FUN(MsgDialogInitStart){
	JSObject* param = J2O(argv[0]);
	memset(&dialog,0,sizeof(dialog));
	pspUtilityDialogCommon base;
	dialog.base=objectToBase(JSVAL_TO_OBJECT(js_getProperty(param,"base")),&base,sizeof(dialog));
	dialog.mode=J2I(js_getProperty(param,"mode"));
	dialog.options=J2I(js_getProperty(param,"options"));
  dialog.errorValue=J2I(js_getProperty(param,"errorValue"));
	char* msg = js_getStringBytes(JSVAL_TO_STRING(js_getProperty(param,"message")));
	if(strlen(msg)<512)
		strcpy(dialog.message,msg);
	else
		strcpy(dialog.message,"String length > 511 bytes");

	*rval = I2J(sceUtilityMsgDialogInitStart(&dialog));
	return JS_TRUE;	
}
pspUtilityNetconfData Netconf;
JS_FUN(NetconfInitStart){
	JSObject* param = J2O(argv[0]);
	memset(&Netconf,0,sizeof(Netconf));
	pspUtilityDialogCommon base;
	Netconf.base=objectToBase(JSVAL_TO_OBJECT(js_getProperty(param,"base")),&base,sizeof(Netconf));
	Netconf.action=J2I(js_getProperty(param,"action"));
	//Netconf.hotspot=J2I(js_getProperty(param,"hotspot"));
	//Netconf.hotspot_connected=J2I(js_getProperty(param,"hotspot_connected"));
  //Netconf.wifisp=J2I(js_getProperty(param,"wifisp"));
	
	//pspUtilityNetconfAdhoc adhocparam;
	//memset(&adhocparam, 0, sizeof(adhocparam));
	//Netconf.adhocparam = &adhocparam;

	*rval = I2J(sceUtilityNetconfInitStart(&Netconf));
	return JS_TRUE;	
}
JS_FUN(NetconfShutdownStart){
	*rval = I2J(sceUtilityNetconfShutdownStart());
	return JS_TRUE;	
}
JS_FUN(NetconfUpdate){
	*rval = I2J(sceUtilityNetconfUpdate(J2I(argv[0])));
	return JS_TRUE;	
}
JS_FUN(NetconfGetStatus){
	*rval = I2J(sceUtilityNetconfGetStatus());
	return JS_TRUE;	
}
static JSPropertiesSpec var[] = {
	{"PSP_UTILITY_ACCEPT_CIRCLE",I2J(PSP_UTILITY_ACCEPT_CIRCLE)},
	{"PSP_UTILITY_ACCEPT_CROSS",I2J(PSP_UTILITY_ACCEPT_CROSS)},
	{"PSP_UTILITY_DIALOG_NONE",I2J(PSP_UTILITY_DIALOG_NONE)},
	{"PSP_UTILITY_DIALOG_INIT",I2J(PSP_UTILITY_DIALOG_INIT)},
	{"PSP_UTILITY_DIALOG_VISIBLE",I2J(PSP_UTILITY_DIALOG_VISIBLE)},
	{"PSP_UTILITY_DIALOG_QUIT",I2J(PSP_UTILITY_DIALOG_QUIT)},
	{"PSP_UTILITY_DIALOG_FINISHED",I2J(PSP_UTILITY_DIALOG_FINISHED)},
	{"PSP_SYSTEMPARAM_ID_STRING_NICKNAME",I2J(PSP_SYSTEMPARAM_ID_STRING_NICKNAME)},
	{"PSP_SYSTEMPARAM_ID_INT_ADHOC_CHANNEL",I2J(PSP_SYSTEMPARAM_ID_INT_ADHOC_CHANNEL)},
	{"PSP_SYSTEMPARAM_ID_INT_WLAN_POWERSAVE",I2J(PSP_SYSTEMPARAM_ID_INT_WLAN_POWERSAVE)},
	{"PSP_SYSTEMPARAM_ID_INT_DATE_FORMAT",I2J(PSP_SYSTEMPARAM_ID_INT_DATE_FORMAT)},
	{"PSP_SYSTEMPARAM_ID_INT_TIME_FORMAT",I2J(PSP_SYSTEMPARAM_ID_INT_TIME_FORMAT)},
	{"PSP_SYSTEMPARAM_ID_INT_TIMEZONE",I2J(PSP_SYSTEMPARAM_ID_INT_TIMEZONE)},
	{"PSP_SYSTEMPARAM_ID_INT_DAYLIGHTSAVINGS",I2J(PSP_SYSTEMPARAM_ID_INT_DAYLIGHTSAVINGS)},
	{"PSP_SYSTEMPARAM_ID_INT_LANGUAGE",I2J(PSP_SYSTEMPARAM_ID_INT_LANGUAGE)},
	{"PSP_SYSTEMPARAM_ID_INT_UNKNOWN",I2J(PSP_SYSTEMPARAM_ID_INT_UNKNOWN)},
	{"PSP_SYSTEMPARAM_RETVAL_OK",I2J(PSP_SYSTEMPARAM_RETVAL_OK)},
	{"PSP_SYSTEMPARAM_RETVAL_FAIL",I2J(PSP_SYSTEMPARAM_RETVAL_FAIL)},
	{"PSP_SYSTEMPARAM_ADHOC_CHANNEL_AUTOMATIC",I2J(PSP_SYSTEMPARAM_ADHOC_CHANNEL_AUTOMATIC)},
	{"PSP_SYSTEMPARAM_ADHOC_CHANNEL_1",I2J(PSP_SYSTEMPARAM_ADHOC_CHANNEL_1)},
	{"PSP_SYSTEMPARAM_ADHOC_CHANNEL_6",I2J(PSP_SYSTEMPARAM_ADHOC_CHANNEL_6)},
	{"PSP_SYSTEMPARAM_WLAN_POWERSAVE_OFF",I2J(PSP_SYSTEMPARAM_WLAN_POWERSAVE_OFF)},
	{"PSP_SYSTEMPARAM_WLAN_POWERSAVE_ON",I2J(PSP_SYSTEMPARAM_WLAN_POWERSAVE_ON)},
	{"PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD",I2J(PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD)},
	{"PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY",I2J(PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY)},
	{"PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY",I2J(PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY)},
	{"PSP_SYSTEMPARAM_TIME_FORMAT_24HR",I2J(PSP_SYSTEMPARAM_TIME_FORMAT_24HR)},
	{"PSP_SYSTEMPARAM_TIME_FORMAT_12HR",I2J(PSP_SYSTEMPARAM_TIME_FORMAT_12HR)},
	{"PSP_SYSTEMPARAM_DAYLIGHTSAVINGS_STD",I2J(PSP_SYSTEMPARAM_DAYLIGHTSAVINGS_STD)},
	{"PSP_SYSTEMPARAM_DAYLIGHTSAVINGS_SAVING",I2J(PSP_SYSTEMPARAM_DAYLIGHTSAVINGS_SAVING)},
	{"PSP_SYSTEMPARAM_LANGUAGE_JAPANESE",I2J(PSP_SYSTEMPARAM_LANGUAGE_JAPANESE)},
	{"PSP_SYSTEMPARAM_LANGUAGE_ENGLISH",I2J(PSP_SYSTEMPARAM_LANGUAGE_ENGLISH)},
	{"PSP_SYSTEMPARAM_LANGUAGE_FRENCH",I2J(PSP_SYSTEMPARAM_LANGUAGE_FRENCH)},
	{"PSP_SYSTEMPARAM_LANGUAGE_SPANISH",I2J(PSP_SYSTEMPARAM_LANGUAGE_SPANISH)},
	{"PSP_SYSTEMPARAM_LANGUAGE_GERMAN",I2J(PSP_SYSTEMPARAM_LANGUAGE_GERMAN)},
	{"PSP_SYSTEMPARAM_LANGUAGE_ITALIAN",I2J(PSP_SYSTEMPARAM_LANGUAGE_ITALIAN)},
	{"PSP_SYSTEMPARAM_LANGUAGE_DUTCH",I2J(PSP_SYSTEMPARAM_LANGUAGE_DUTCH)},
	{"PSP_SYSTEMPARAM_LANGUAGE_PORTUGUESE",I2J(PSP_SYSTEMPARAM_LANGUAGE_PORTUGUESE)},
	{"PSP_SYSTEMPARAM_LANGUAGE_RUSSIAN",I2J(PSP_SYSTEMPARAM_LANGUAGE_RUSSIAN)},
	{"PSP_SYSTEMPARAM_LANGUAGE_KOREAN",I2J(PSP_SYSTEMPARAM_LANGUAGE_KOREAN)},
	{"PSP_SYSTEMPARAM_LANGUAGE_CHINESE_TRADITIONAL",I2J(PSP_SYSTEMPARAM_LANGUAGE_CHINESE_TRADITIONAL)},
	{"PSP_SYSTEMPARAM_LANGUAGE_CHINESE_SIMPLIFIED",I2J(PSP_SYSTEMPARAM_LANGUAGE_CHINESE_SIMPLIFIED)},
	{"PSP_USB_MODULE_PSPCM",I2J(PSP_USB_MODULE_PSPCM)},
	{"PSP_USB_MODULE_ACC",I2J(PSP_USB_MODULE_ACC)},
	{"PSP_USB_MODULE_MIC",I2J(PSP_USB_MODULE_MIC)},
	{"PSP_USB_MODULE_CAM",I2J(PSP_USB_MODULE_CAM)},
	{"PSP_USB_MODULE_GPS",I2J(PSP_USB_MODULE_GPS)},
	{"PSP_AV_MODULE_AVCODEC",I2J(PSP_AV_MODULE_AVCODEC)},
	{"PSP_AV_MODULE_SASCORE",I2J(PSP_AV_MODULE_SASCORE)},
	{"PSP_AV_MODULE_ATRAC3PLUS",I2J(PSP_AV_MODULE_ATRAC3PLUS)},
	{"PSP_AV_MODULE_MPEGBASE",I2J(PSP_AV_MODULE_MPEGBASE)},
	{"PSP_AV_MODULE_MP3",I2J(PSP_AV_MODULE_MP3)},
	{"PSP_AV_MODULE_VAUDIO",I2J(PSP_AV_MODULE_VAUDIO)},
	{"PSP_AV_MODULE_AAC",I2J(PSP_AV_MODULE_AAC)},
	{"PSP_AV_MODULE_G729",I2J(PSP_AV_MODULE_G729)},
	{"PSP_NET_MODULE_COMMON",I2J(PSP_NET_MODULE_COMMON)},
	{"PSP_NET_MODULE_ADHOC",I2J(PSP_NET_MODULE_ADHOC)},
	{"PSP_NET_MODULE_INET",I2J(PSP_NET_MODULE_INET)},
	{"PSP_NET_MODULE_PARSEURI",I2J(PSP_NET_MODULE_PARSEURI)},
	{"PSP_NET_MODULE_PARSEHTTP",I2J(PSP_NET_MODULE_PARSEHTTP)},
	{"PSP_NET_MODULE_HTTP",I2J(PSP_NET_MODULE_HTTP)},
	{"PSP_NET_MODULE_SSL",I2J(PSP_NET_MODULE_SSL)},
	{"PSP_UTILITY_GAMESHARING_MODE_SINGLE",I2J(PSP_UTILITY_GAMESHARING_MODE_SINGLE)},
	{"PSP_UTILITY_GAMESHARING_MODE_MULTIPLE",I2J(PSP_UTILITY_GAMESHARING_MODE_MULTIPLE)},
	{"PSP_UTILITY_GAMESHARING_DATA_TYPE_FILE",I2J(PSP_UTILITY_GAMESHARING_DATA_TYPE_FILE)},
	{"PSP_UTILITY_GAMESHARING_DATA_TYPE_MEMORY",I2J(PSP_UTILITY_GAMESHARING_DATA_TYPE_MEMORY)},
	{"PSP_UTILITY_HTMLVIEWER_DISCONNECTMODE_ENABLE",I2J(PSP_UTILITY_HTMLVIEWER_DISCONNECTMODE_ENABLE)},
	{"PSP_UTILITY_HTMLVIEWER_DISCONNECTMODE_DISABLE",I2J(PSP_UTILITY_HTMLVIEWER_DISCONNECTMODE_DISABLE)},
	{"PSP_UTILITY_HTMLVIEWER_DISCONNECTMODE_CONFIRM",I2J(PSP_UTILITY_HTMLVIEWER_DISCONNECTMODE_CONFIRM)},
	{"PSP_UTILITY_HTMLVIEWER_INTERFACEMODE_FULL",I2J(PSP_UTILITY_HTMLVIEWER_INTERFACEMODE_FULL)},
	{"PSP_UTILITY_HTMLVIEWER_INTERFACEMODE_LIMITED",I2J(PSP_UTILITY_HTMLVIEWER_INTERFACEMODE_LIMITED)},
	{"PSP_UTILITY_HTMLVIEWER_INTERFACEMODE_NONE",I2J(PSP_UTILITY_HTMLVIEWER_INTERFACEMODE_NONE)},
	{"PSP_UTILITY_HTMLVIEWER_COOKIEMODE_DISABLED",I2J(PSP_UTILITY_HTMLVIEWER_COOKIEMODE_DISABLED)},
	{"PSP_UTILITY_HTMLVIEWER_COOKIEMODE_ENABLED",I2J(PSP_UTILITY_HTMLVIEWER_COOKIEMODE_ENABLED)},
	{"PSP_UTILITY_HTMLVIEWER_COOKIEMODE_CONFIRM",I2J(PSP_UTILITY_HTMLVIEWER_COOKIEMODE_CONFIRM)},
	{"PSP_UTILITY_HTMLVIEWER_COOKIEMODE_DEFAULT",I2J(PSP_UTILITY_HTMLVIEWER_COOKIEMODE_DEFAULT)},
	{"PSP_UTILITY_HTMLVIEWER_TEXTSIZE_LARGE",I2J(PSP_UTILITY_HTMLVIEWER_TEXTSIZE_LARGE)},
	{"PSP_UTILITY_HTMLVIEWER_TEXTSIZE_NORMAL",I2J(PSP_UTILITY_HTMLVIEWER_TEXTSIZE_NORMAL)},
	{"PSP_UTILITY_HTMLVIEWER_TEXTSIZE_SMALL",I2J(PSP_UTILITY_HTMLVIEWER_TEXTSIZE_SMALL)},
	{"PSP_UTILITY_HTMLVIEWER_DISPLAYMODE_NORMAL",I2J(PSP_UTILITY_HTMLVIEWER_DISPLAYMODE_NORMAL)},
	{"PSP_UTILITY_HTMLVIEWER_DISPLAYMODE_FIT",I2J(PSP_UTILITY_HTMLVIEWER_DISPLAYMODE_FIT)},
	{"PSP_UTILITY_HTMLVIEWER_DISPLAYMODE_SMART_FIT",I2J(PSP_UTILITY_HTMLVIEWER_DISPLAYMODE_SMART_FIT)},
	{"PSP_UTILITY_HTMLVIEWER_CONNECTMODE_LAST",I2J(PSP_UTILITY_HTMLVIEWER_CONNECTMODE_LAST)},
	{"PSP_UTILITY_HTMLVIEWER_CONNECTMODE_MANUAL_ONCE",I2J(PSP_UTILITY_HTMLVIEWER_CONNECTMODE_MANUAL_ONCE)},
	{"PSP_UTILITY_HTMLVIEWER_CONNECTMODE_MANUAL_ALL",I2J(PSP_UTILITY_HTMLVIEWER_CONNECTMODE_MANUAL_ALL)},
	{"PSP_UTILITY_HTMLVIEWER_OPEN_SCE_START_PAGE",I2J(PSP_UTILITY_HTMLVIEWER_OPEN_SCE_START_PAGE)},
	{"PSP_UTILITY_HTMLVIEWER_DISABLE_STARTUP_LIMITS",I2J(PSP_UTILITY_HTMLVIEWER_DISABLE_STARTUP_LIMITS)},
	{"PSP_UTILITY_HTMLVIEWER_DISABLE_EXIT_DIALOG",I2J(PSP_UTILITY_HTMLVIEWER_DISABLE_EXIT_DIALOG)},
	{"PSP_UTILITY_HTMLVIEWER_DISABLE_CURSOR",I2J(PSP_UTILITY_HTMLVIEWER_DISABLE_CURSOR)},
	{"PSP_UTILITY_HTMLVIEWER_DISABLE_DOWNLOAD_COMPLETE_DIALOG",I2J(PSP_UTILITY_HTMLVIEWER_DISABLE_DOWNLOAD_COMPLETE_DIALOG)},
	{"PSP_UTILITY_HTMLVIEWER_DISABLE_DOWNLOAD_START_DIALOG",I2J(PSP_UTILITY_HTMLVIEWER_DISABLE_DOWNLOAD_START_DIALOG)},
	{"PSP_UTILITY_HTMLVIEWER_DISABLE_DOWNLOAD_DESTINATION_DIALOG",I2J(PSP_UTILITY_HTMLVIEWER_DISABLE_DOWNLOAD_DESTINATION_DIALOG)},
	{"PSP_UTILITY_HTMLVIEWER_LOCK_DOWNLOAD_DESTINATION_DIALOG",I2J(PSP_UTILITY_HTMLVIEWER_LOCK_DOWNLOAD_DESTINATION_DIALOG)},
	{"PSP_UTILITY_HTMLVIEWER_DISABLE_TAB_DISPLAY",I2J(PSP_UTILITY_HTMLVIEWER_DISABLE_TAB_DISPLAY)},
	{"PSP_UTILITY_HTMLVIEWER_ENABLE_ANALOG_HOLD",I2J(PSP_UTILITY_HTMLVIEWER_ENABLE_ANALOG_HOLD)},
	{"PSP_UTILITY_HTMLVIEWER_ENABLE_FLASH",I2J(PSP_UTILITY_HTMLVIEWER_ENABLE_FLASH)},
	{"PSP_UTILITY_HTMLVIEWER_DISABLE_LRTRIGGER",I2J(PSP_UTILITY_HTMLVIEWER_DISABLE_LRTRIGGER)},
	{"PSP_UTILITY_SAVEDATA_AUTOLOAD",I2J(PSP_UTILITY_SAVEDATA_AUTOLOAD)},
	{"PSP_UTILITY_SAVEDATA_AUTOSAVE",I2J(PSP_UTILITY_SAVEDATA_AUTOSAVE)},
	{"PSP_UTILITY_SAVEDATA_LOAD",I2J(PSP_UTILITY_SAVEDATA_LOAD)},
	{"PSP_UTILITY_SAVEDATA_SAVE",I2J(PSP_UTILITY_SAVEDATA_SAVE)},
	{"PSP_UTILITY_SAVEDATA_LISTLOAD",I2J(PSP_UTILITY_SAVEDATA_LISTLOAD)},
	{"PSP_UTILITY_SAVEDATA_LISTSAVE",I2J(PSP_UTILITY_SAVEDATA_LISTSAVE)},
	{"PSP_UTILITY_SAVEDATA_LISTDELETE",I2J(PSP_UTILITY_SAVEDATA_LISTDELETE)},
	{"PSP_UTILITY_SAVEDATA_DELETE",I2J(PSP_UTILITY_SAVEDATADELETE)},
	{"PSP_UTILITY_SAVEDATADELETE",I2J(PSP_UTILITY_SAVEDATADELETE)},/*missing underline ?*/
	{"PSP_UTILITY_SAVEDATA_FOCUS_UNKNOWN",I2J(PSP_UTILITY_SAVEDATA_FOCUS_UNKNOWN)},
	{"PSP_UTILITY_SAVEDATA_FOCUS_FIRSTLIST",I2J(PSP_UTILITY_SAVEDATA_FOCUS_FIRSTLIST)},
	{"PSP_UTILITY_SAVEDATA_FOCUS_LASTLIST",I2J(PSP_UTILITY_SAVEDATA_FOCUS_LASTLIST)},
	{"PSP_UTILITY_SAVEDATA_FOCUS_LATEST",I2J(PSP_UTILITY_SAVEDATA_FOCUS_LATEST)},
	{"PSP_UTILITY_SAVEDATA_FOCUS_OLDEST",I2J(PSP_UTILITY_SAVEDATA_FOCUS_OLDEST)},
	{"PSP_UTILITY_SAVEDATA_FOCUS_UNKNOWN2",I2J(PSP_UTILITY_SAVEDATA_FOCUS_UNKNOWN2)},
	{"PSP_UTILITY_SAVEDATA_FOCUS_UNKNOWN3",I2J(PSP_UTILITY_SAVEDATA_FOCUS_UNKNOWN3)},
	{"PSP_UTILITY_SAVEDATA_FOCUS_FIRSTEMPTY",I2J(PSP_UTILITY_SAVEDATA_FOCUS_FIRSTEMPTY)},
	{"PSP_UTILITY_SAVEDATA_FOCUS_LASTEMPTY",I2J(PSP_UTILITY_SAVEDATA_FOCUS_LASTEMPTY)},
	{"PSP_UTILITY_MSGDIALOG_MODE_ERROR",I2J(PSP_UTILITY_MSGDIALOG_MODE_ERROR)},
	{"PSP_UTILITY_MSGDIALOG_MODE_TEXT",I2J(PSP_UTILITY_MSGDIALOG_MODE_TEXT)},
	{"PSP_UTILITY_MSGDIALOG_OPTION_ERROR",I2J(PSP_UTILITY_MSGDIALOG_OPTION_ERROR)},
	{"PSP_UTILITY_MSGDIALOG_OPTION_TEXT",I2J(PSP_UTILITY_MSGDIALOG_OPTION_TEXT)},
	{"PSP_UTILITY_MSGDIALOG_OPTION_YESNO_BUTTONS",I2J(PSP_UTILITY_MSGDIALOG_OPTION_YESNO_BUTTONS)},
	{"PSP_UTILITY_MSGDIALOG_OPTION_DEFAULT_NO",I2J(PSP_UTILITY_MSGDIALOG_OPTION_DEFAULT_NO)},
	{"PSP_UTILITY_MSGDIALOG_RESULT_UNKNOWN1",I2J(PSP_UTILITY_MSGDIALOG_RESULT_UNKNOWN1)},
	{"PSP_UTILITY_MSGDIALOG_RESULT_YES",I2J(PSP_UTILITY_MSGDIALOG_RESULT_YES)},
	{"PSP_UTILITY_MSGDIALOG_RESULT_NO",I2J(PSP_UTILITY_MSGDIALOG_RESULT_NO)},
	{"PSP_UTILITY_MSGDIALOG_RESULT_BACK",I2J(PSP_UTILITY_MSGDIALOG_RESULT_BACK)},
	{"PSP_NETCONF_ACTION_CONNECTAP",I2J(PSP_NETCONF_ACTION_CONNECTAP)},
	{"PSP_NETCONF_ACTION_DISPLAYSTATUS",I2J(PSP_NETCONF_ACTION_DISPLAYSTATUS)},
	{"PSP_NETCONF_ACTION_CONNECT_ADHOC",I2J(PSP_NETCONF_ACTION_CONNECT_ADHOC)},
	{"PSP_NETPARAM_NAME",I2J(PSP_NETPARAM_NAME)},
	{"PSP_NETPARAM_SSID",I2J(PSP_NETPARAM_SSID)},
	{"PSP_NETPARAM_SECURE",I2J(PSP_NETPARAM_SECURE)},
	{"PSP_NETPARAM_WEPKEY",I2J(PSP_NETPARAM_WEPKEY)},
	{"PSP_NETPARAM_IS_STATIC_IP",I2J(PSP_NETPARAM_IS_STATIC_IP)},
	{"PSP_NETPARAM_IP",I2J(PSP_NETPARAM_IP)},
	{"PSP_NETPARAM_NETMASK",I2J(PSP_NETPARAM_NETMASK)},
	{"PSP_NETPARAM_ROUTE",I2J(PSP_NETPARAM_ROUTE)},
	{"PSP_NETPARAM_MANUAL_DNS",I2J(PSP_NETPARAM_MANUAL_DNS)},
	{"PSP_NETPARAM_PRIMARYDNS",I2J(PSP_NETPARAM_PRIMARYDNS)},
	{"PSP_NETPARAM_SECONDARYDNS",I2J(PSP_NETPARAM_SECONDARYDNS)},
	{"PSP_NETPARAM_PROXY_USER",I2J(PSP_NETPARAM_PROXY_USER)},
	{"PSP_NETPARAM_PROXY_PASS",I2J(PSP_NETPARAM_PROXY_PASS)},
	{"PSP_NETPARAM_USE_PROXY",I2J(PSP_NETPARAM_USE_PROXY)},
	{"PSP_NETPARAM_PROXY_SERVER",I2J(PSP_NETPARAM_PROXY_SERVER)},
	{"PSP_NETPARAM_PROXY_PORT",I2J(PSP_NETPARAM_PROXY_PORT)},
	{"PSP_NETPARAM_UNKNOWN1",I2J(PSP_NETPARAM_UNKNOWN1)},
	{"PSP_NETPARAM_UNKNOWN2",I2J(PSP_NETPARAM_UNKNOWN2)},
	{"PSP_NETPARAM_ERROR_BAD_NETCONF",I2J(PSP_NETPARAM_ERROR_BAD_NETCONF)},
	{"PSP_NETPARAM_ERROR_BAD_PARAM",I2J(PSP_NETPARAM_ERROR_BAD_PARAM)},
	{"PSP_UTILITY_OSK_LANGUAGE_DEFAULT",I2J(PSP_UTILITY_OSK_LANGUAGE_DEFAULT)},
	{"PSP_UTILITY_OSK_LANGUAGE_JAPANESE",I2J(PSP_UTILITY_OSK_LANGUAGE_JAPANESE)},
	{"PSP_UTILITY_OSK_LANGUAGE_ENGLISH",I2J(PSP_UTILITY_OSK_LANGUAGE_ENGLISH)},
	{"PSP_UTILITY_OSK_LANGUAGE_FRENCH",I2J(PSP_UTILITY_OSK_LANGUAGE_FRENCH)},
	{"PSP_UTILITY_OSK_LANGUAGE_SPANISH",I2J(PSP_UTILITY_OSK_LANGUAGE_SPANISH)},
	{"PSP_UTILITY_OSK_LANGUAGE_GERMAN",I2J(PSP_UTILITY_OSK_LANGUAGE_GERMAN)},
	{"PSP_UTILITY_OSK_LANGUAGE_ITALIAN",I2J(PSP_UTILITY_OSK_LANGUAGE_ITALIAN)},
	{"PSP_UTILITY_OSK_LANGUAGE_DUTCH",I2J(PSP_UTILITY_OSK_LANGUAGE_DUTCH)},
	{"PSP_UTILITY_OSK_LANGUAGE_PORTUGESE",I2J(PSP_UTILITY_OSK_LANGUAGE_PORTUGESE)},
	{"PSP_UTILITY_OSK_LANGUAGE_RUSSIAN",I2J(PSP_UTILITY_OSK_LANGUAGE_RUSSIAN)},
	{"PSP_UTILITY_OSK_LANGUAGE_KOREAN",I2J(PSP_UTILITY_OSK_LANGUAGE_KOREAN)},
	{"PSP_UTILITY_OSK_DIALOG_NONE",I2J(PSP_UTILITY_OSK_DIALOG_NONE)},
	{"PSP_UTILITY_OSK_DIALOG_INITING",I2J(PSP_UTILITY_OSK_DIALOG_INITING)},
	{"PSP_UTILITY_OSK_DIALOG_INITED",I2J(PSP_UTILITY_OSK_DIALOG_INITED)},
	{"PSP_UTILITY_OSK_DIALOG_VISIBLE",I2J(PSP_UTILITY_OSK_DIALOG_VISIBLE)},
	{"PSP_UTILITY_OSK_DIALOG_QUIT",I2J(PSP_UTILITY_OSK_DIALOG_QUIT)},
	{"PSP_UTILITY_OSK_DIALOG_FINISHED",I2J(PSP_UTILITY_OSK_DIALOG_FINISHED)},
	{"PSP_UTILITY_OSK_RESULT_UNCHANGED",I2J(PSP_UTILITY_OSK_RESULT_UNCHANGED)},
	{"PSP_UTILITY_OSK_RESULT_CANCELLED",I2J(PSP_UTILITY_OSK_RESULT_CANCELLED)},
	{"PSP_UTILITY_OSK_RESULT_CHANGED",I2J(PSP_UTILITY_OSK_RESULT_CHANGED)},
	{"PSP_UTILITY_OSK_INPUTTYPE_ALL",I2J(PSP_UTILITY_OSK_INPUTTYPE_ALL)},
	{"PSP_UTILITY_OSK_INPUTTYPE_LATIN_DIGIT",I2J(PSP_UTILITY_OSK_INPUTTYPE_LATIN_DIGIT)},
	{"PSP_UTILITY_OSK_INPUTTYPE_LATIN_SYMBOL",I2J(PSP_UTILITY_OSK_INPUTTYPE_LATIN_SYMBOL)},
	{"PSP_UTILITY_OSK_INPUTTYPE_LATIN_LOWERCASE",I2J(PSP_UTILITY_OSK_INPUTTYPE_LATIN_LOWERCASE)},
	{"PSP_UTILITY_OSK_INPUTTYPE_LATIN_UPPERCASE",I2J(PSP_UTILITY_OSK_INPUTTYPE_LATIN_UPPERCASE)},
	{"PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_DIGIT",I2J(PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_DIGIT)},
	{"PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_SYMBOL",I2J(PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_SYMBOL)},
	{"PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_LOWERCASE",I2J(PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_LOWERCASE)},
	{"PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_UPPERCASE",I2J(PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_UPPERCASE)},
	{"PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_HIRAGANA",I2J(PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_HIRAGANA)},
	{"PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_HALF_KATAKANA",I2J(PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_HALF_KATAKANA)},
	{"PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_KATAKANA",I2J(PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_KATAKANA)},
	{"PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_KANJI",I2J(PSP_UTILITY_OSK_INPUTTYPE_JAPANESE_KANJI)},
	{"PSP_UTILITY_OSK_INPUTTYPE_RUSSIAN_LOWERCASE",I2J(PSP_UTILITY_OSK_INPUTTYPE_RUSSIAN_LOWERCASE)},
	{"PSP_UTILITY_OSK_INPUTTYPE_RUSSIAN_UPPERCASE",I2J(PSP_UTILITY_OSK_INPUTTYPE_RUSSIAN_UPPERCASE)},
	{"PSP_UTILITY_OSK_INPUTTYPE_KOREAN",I2J(PSP_UTILITY_OSK_INPUTTYPE_KOREAN)},
	{"PSP_UTILITY_OSK_INPUTTYPE_URL",I2J(PSP_UTILITY_OSK_INPUTTYPE_URL)},
	{"PSP_MODULE_NET_COMMON",I2J(PSP_MODULE_NET_COMMON)},
	{"PSP_MODULE_NET_ADHOC",I2J(PSP_MODULE_NET_ADHOC)},
	{"PSP_MODULE_NET_INET",I2J(PSP_MODULE_NET_INET)},
	{"PSP_MODULE_NET_PARSEURI",I2J(PSP_MODULE_NET_PARSEURI)},
	{"PSP_MODULE_NET_PARSEHTTP",I2J(PSP_MODULE_NET_PARSEHTTP)},
	{"PSP_MODULE_NET_HTTP",I2J(PSP_MODULE_NET_HTTP)},
	{"PSP_MODULE_NET_SSL",I2J(PSP_MODULE_NET_SSL)},
	{"PSP_MODULE_USB_PSPCM",I2J(PSP_MODULE_USB_PSPCM)},
	{"PSP_MODULE_USB_MIC",I2J(PSP_MODULE_USB_MIC)},
	{"PSP_MODULE_USB_CAM",I2J(PSP_MODULE_USB_CAM)},
	{"PSP_MODULE_USB_GPS",I2J(PSP_MODULE_USB_GPS)},
	{"PSP_MODULE_AV_AVCODEC",I2J(PSP_MODULE_AV_AVCODEC)},
	{"PSP_MODULE_AV_SASCORE",I2J(PSP_MODULE_AV_SASCORE)},
	{"PSP_MODULE_AV_ATRAC3PLUS",I2J(PSP_MODULE_AV_ATRAC3PLUS)},
	{"PSP_MODULE_AV_MPEGBASE",I2J(PSP_MODULE_AV_MPEGBASE)},
	{"PSP_MODULE_AV_MP3",I2J(PSP_MODULE_AV_MP3)},
	{"PSP_MODULE_AV_VAUDIO",I2J(PSP_MODULE_AV_VAUDIO)},
	{"PSP_MODULE_AV_AAC",I2J(PSP_MODULE_AV_AAC)},
	{"PSP_MODULE_AV_G729",I2J(PSP_MODULE_AV_G729)},
	{"PSP_MODULE_NP_COMMON",I2J(PSP_MODULE_NP_COMMON)},
	{"PSP_MODULE_NP_SERVICE",I2J(PSP_MODULE_NP_SERVICE)},
	{"PSP_MODULE_NP_MATCHING2",I2J(PSP_MODULE_NP_MATCHING2)},
	{"PSP_MODULE_NP_DRM",I2J(PSP_MODULE_NP_DRM)},
	{"PSP_MODULE_IRDA",I2J(PSP_MODULE_IRDA)},
	{0}
};
static JSFunctionSpec functions[] = {
	{"LoadAvModule",LoadAvModule,1},
	{"UnloadAvModule",UnloadAvModule,1},
	{"LoadNetModule",LoadNetModule,1},
	{"UnloadNetModule",UnloadNetModule,1},
	{"LoadUsbModule",LoadUsbModule,1},
	{"UnloadUsbModule",UnloadUsbModule,1},
	{"LoadModule",LoadModule,1},
	{"UnloadModule",UnloadModule,1},
	{"GameSharingUpdate",GameSharingUpdate,0},
	{"GameSharingGetStatus",GameSharingGetStatus,0},
	{"GameSharingShutdownStart",GameSharingShutdownStart,0},
	{"MsgDialogInitStart",MsgDialogInitStart,1},
	{"MsgDialogShutdownStart",MsgDialogShutdownStart,0},
	{"MsgDialogGetStatus",MsgDialogGetStatus,0},
	{"MsgDialogUpdate",MsgDialogUpdate,0},
	{"MsgDialogAbort",MsgDialogAbort,0},
	{"GetSystemParamInt",GetSystemParamInt,1},
	{"SetSystemParamInt",SetSystemParamInt,2},
	{"GetSystemParamString",GetSystemParamString,1},
	{"SetSystemParamString",SetSystemParamString,2},
	{"NetconfInitStart",NetconfInitStart,2},
	{"NetconfShutdownStart",NetconfShutdownStart,0},
	{"NetconfUpdate",NetconfUpdate,1},
	{"NetconfGetStatus",NetconfGetStatus,0},
	{0}
};
int module_start(SceSize args, void *argp){
	js_addModule(functions,0,0,var);
	return 0;
}
int module_stop(SceSize args, void *argp){
	return 0;
}
